version: "3.8"

services:
  postgres_db:
    ports:
      - "5432:5432"
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bankingTest
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_banking
    networks:
      - rest_api

networks:
  banking:
    name: banking
  rest_api:
    name: rest_api
